### ISSUE TITLE
Player Extension

### ISSUE THREAD

**Issue by grayinot** [jmir1/tachiyomi-mi#1037]
### Steps to reproduce

Go to setting and enable player Extension and select player you prefer

Play any anime

App crashes 

### Expected behavior

Aniume should play on Extention player

### Actual behavior

App crashes

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Device

Poco x3 nfc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
are you on stable or the preview?
