### ISSUE TITLE
Third-party repos can't be added

### ISSUE THREAD

**Issue by mklive** [jmir1/tachiyomi-mi#1681]
### Steps to reproduce

Go to extension anime/manga
Try to add a valid repo URL

### Expected behavior

It should add repo

### Actual behavior

Aniyomi says URL is invalid

### Aniyomi version

r7714

### Android version

Android 14

### Device

Google Pixel 7 Pro

### Other details

Third-party repos were cleared after update also

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the extension's repository.
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
This is because the repo doesn't contain all the necessary information to be recognized. It's an issue with the repo, not aniyomi.
