### ISSUE TITLE
Aniyomi crashes after removing anime/manga from library

### ISSUE THREAD

**Issue by ghost** [jmir1/tachiyomi-mi#190]
### Steps to reproduce

1. Add some anime and/or manga to your library
2. Removing it holding the element and clicking the remove button
2.1 Removing it opening the info page and clicking on 'In library' button and going back

### Expected behavior

Not to crash the app after removing the anime/manga from your library

### Actual behavior

After removing the anime/manga from your library the app closes and after reopening the app the elements are removed

### Crash logs

--------- beginning of system
10-10 14:14:10.246   796  7677 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
--------- beginning of main
--------- beginning of crash
10-10 14:14:21.690   796   796 E AndroidRuntime: FATAL EXCEPTION: main
10-10 14:14:21.690   796   796 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 796
10-10 14:14:21.690   796   796 E AndroidRuntime: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:3)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-10 14:14:21.690   796   796 E AndroidRuntime: Caused by: rx.exceptions.OnErrorNotImplementedException: Index: 0
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:2)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:1)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:1)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:2)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:4)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:6)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:3)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:2)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.drain(OnSubscribeCombineLatest.java:17)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.combine(OnSubscribeCombineLatest.java:17)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeCombineLatest$CombinerSubscriber.onNext(OnSubscribeCombineLatest.java:2)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:2)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:2)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.internal.operators.OperatorMaterialize$ParentSubscriber.onNext(OperatorMaterialize.java:1)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:8)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:1)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	... 7 more
10-10 14:14:21.690   796   796 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: Index: 0
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at java.util.Collections$EmptyList.get(Collections.java:4511)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.animelib.AnimelibAdapter.getViewType(AnimelibAdapter.kt:1)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at eu.kanade.tachiyomi.widget.RecyclerViewPagerAdapter.destroyView(RecyclerViewPagerAdapter.kt:2)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at com.nightlynexus.viewstatepageradapter.ViewStatePagerAdapter.destroyItem(ViewStatePagerAdapter.java:2)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:11)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(ViewPager.java:1)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:3)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.animelib.AnimelibAdapter.setCategories(AnimelibAdapter.kt:3)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.animelib.AnimelibController.onNextAnimelibUpdate(AnimelibController.kt:15)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.animelib.AnimelibPresenter$subscribeAnimelib$4.invoke(AnimelibPresenter.kt:3)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.animelib.AnimelibPresenter$subscribeAnimelib$4.invoke(AnimelibPresenter.kt:1)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.anime.AnimePresenter$$ExternalSyntheticLambda17.call(Unknown Source:4)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at nucleus.presenter.RxPresenter$4.call(RxPresenter.java:4)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:1)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:2)
10-10 14:14:21.690   796   796 E AndroidRuntime: 	... 16 more
10-10 14:14:29.496  6849  7853 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
10-10 14:14:29.652  6849  7876 E SQLiteLog: (284) automatic index on C(anime_id)
10-10 14:14:29.652  6849  7876 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
10-10 14:14:40.677  7946  7971 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
10-10 14:14:46.899  6851  8037 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
10-10 14:14:47.058  6851  8060 E SQLiteLog: (284) automatic index on C(anime_id)
10-10 14:14:47.058  6851  8060 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
10-10 14:15:44.050  6851  8245 E SQLiteLog: (284) automatic index on C(manga_id)
10-10 14:15:44.050  6851  8245 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: FATAL EXCEPTION: main
10-10 14:15:47.122  6851  6851 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 6851
10-10 14:15:47.122  6851  6851 E AndroidRuntime: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:3)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: Caused by: rx.exceptions.OnErrorNotImplementedException: Index: 0
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:2)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:1)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:1)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:2)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:4)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:6)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:3)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:2)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.drain(OnSubscribeCombineLatest.java:17)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeCombineLatest$LatestCoordinator.combine(OnSubscribeCombineLatest.java:17)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeCombineLatest$CombinerSubscriber.onNext(OnSubscribeCombineLatest.java:2)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:2)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:2)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.internal.operators.OperatorMaterialize$ParentSubscriber.onNext(OperatorMaterialize.java:1)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:8)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:1)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	... 7 more
10-10 14:15:47.122  6851  6851 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: Index: 0
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at java.util.Collections$EmptyList.get(Collections.java:4511)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibraryAdapter.getViewType(LibraryAdapter.kt:1)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at eu.kanade.tachiyomi.widget.RecyclerViewPagerAdapter.destroyView(RecyclerViewPagerAdapter.kt:2)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at com.nightlynexus.viewstatepageradapter.ViewStatePagerAdapter.destroyItem(ViewStatePagerAdapter.java:2)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager.dataSetChanged(ViewPager.java:11)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at androidx.viewpager.widget.ViewPager$PagerObserver.onChanged(ViewPager.java:1)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at androidx.viewpager.widget.PagerAdapter.notifyDataSetChanged(PagerAdapter.java:3)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibraryAdapter.setCategories(LibraryAdapter.kt:3)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibraryController.onNextLibraryUpdate(LibraryController.kt:15)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibraryPresenter$subscribeLibrary$4.invoke(LibraryPresenter.kt:3)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.library.LibraryPresenter$subscribeLibrary$4.invoke(LibraryPresenter.kt:1)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.more.MoreController$$ExternalSyntheticLambda0.call(Unknown Source:104)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at nucleus.presenter.RxPresenter$4.call(RxPresenter.java:4)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:1)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:2)
10-10 14:15:47.122  6851  6851 E AndroidRuntime: 	... 16 more
10-10 14:15:49.264  6852  8279 E ActivityThread: Failed to find provider info for com.google.android.gms.chimera
10-10 14:15:49.422  6852  8302 E SQLiteLog: (284) automatic index on C(anime_id)
10-10 14:15:49.422  6852  8302 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
App version: 0.12.3.2 (standard, 940c08a, 69, 2021-10-09T21:21Z)
Android version: 11 (SDK 30)
Android build ID: lineage_vayu-userdebug 11 RQ3A.210905.001 10035732
Device brand: POCO
Device manufacturer: Xiaomi
Device name: vayu
Device model: M2102J20SG
Device product name: lineage_vayu

### Aniyomi version

0.12.3.2

### Android version

Android 11

### Device

Xiaomi Poco X3 Pro

### Other details

- Using LineageOs 18.1 without Gapps.
- This issue happens in 0.12.3.1 version too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
i just noticed that it also happens on tachiyomi, so i opened a pr there, too.

**Comment by Relwi** [comment]
Yep, can confirm, I reinstalled the app and it crashes too.
