### ISSUE TITLE
Use UPDATE_PACKAGES_WITHOUT_USER_ACTION for automatic background app updates

### ISSUE THREAD

**Issue by VictorVow** [jmir1/tachiyomi-mi#191]
### Describe your suggested feature

[This post](https://www.xda-developers.com/android-12-alternative-app-stores-update-apps-background/) describes how apps are now able to update themselves automatically in the background without prompting the user. This would be preferable than having to be prompted each time to update the main app, as well as the extensions.

Upstream Tachiyomi has already implemented this for extensions and is considering it for the main app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
I think you are mistaken. Tachiyomi does NOT update extensions automatically. What it does do is update extensions without you having to confirm the installation in a dialogue, but only if you have Android 12
