### ISSUE TITLE
[Feature Request] add Extension Icons

### ISSUE THREAD

**Issue by as280093** [jmir1/tachiyomi-mi#27]
4Anime : [4Anime_Icon.zip](https://github.com/jmir1/tachiyomi-mi/files/6549008/ic_launcher.zip)
Tenshi.moe : [Tenshi.moe_Icon.zip](https://github.com/jmir1/tachiyomi-mi/files/6549015/ic_launcher.1.zip)
2dgirls.tech : [2dgirls.tech_icon.zip](https://github.com/jmir1/tachiyomi-mi/files/6549017/ic_launcher.zip)

**Comment by jmir1** [comment]
thanks so much, you are a legend!
