### ISSUE TITLE
[Feature Request] - Download support

### ISSUE THREAD

**Issue by Memezaa** [jmir1/tachiyomi-mi#28]
Currently, on the 4anime source downloading doesn't work. This might be a source issue or an app issue.

**Comment by jmir1** [comment]
this just wasn't implemented yet.
it's now almost done.
downloading works but there are some minor bugs with it.

**Comment by jmir1** [comment]
with https://github.com/jmir1/tachiyomi-mi/commit/1a495266fbbf7dd203b666ed560e8dc0314b3fc8, most of the bugs should be fixed.
