### ISSUE TITLE
[Feature Request] Horizontal Mode By Default When Playing A Video

### ISSUE THREAD

**Issue by 8227846265** [jmir1/tachiyomi-mi#29]
## Why/User Benefit/User Problem
Currently the video player plays the episode on portrait mode. 

## What/Requirements
The video player can be played on horizontal mode for better viewing experience

**Comment by jmir1** [comment]
already done

**Comment by 8227846265** [comment]
May I know where could I enable this on the app?

**Comment by S0T0N0** [comment]
> May I know where could I enable this on the app?

Got to settings then player

**Comment by 8227846265** [comment]
I checked the Settings. It's not available 

![Screenshot_20210527-135101_Tachiyomi-MI](https://user-images.githubusercontent.com/66582769/119773150-c74ce300-bef2-11eb-9edb-ff97ee5c8ca9.png)

![Screenshot_20210527-135254_Tachiyomi-MI](https://user-images.githubusercontent.com/66582769/119773214-e0ee2a80-bef2-11eb-8513-44ced4ead7fc.png)

**Comment by S0T0N0** [comment]
Did you updated the app?

**Comment by 8227846265** [comment]
Oh, I thought the one available in the Release Page is the latest. 

It seems About > Update uses a different source since there's a new update prompt for it.

**Comment by 8227846265** [comment]
Found the Player in the Settings now. Thanks for the help.
