### ISSUE TITLE
[Feature Request] <Add CBZ support>

### ISSUE THREAD

**Issue by SanOtaku09** [jmir1/tachiyomi-mi#31]
Add CBZ compression for Manga
Just like sy
![Screenshot_2021-05-29-11-57-09-769_eu kanade tachiyomi sy](https://user-images.githubusercontent.com/61407097/120060395-3fdbad00-c075-11eb-9a9f-eec36858b798.jpg)

**Comment by jmir1** [comment]
why not use sy if you want that feature?
