### ISSUE TITLE
Dopebox not playing movie

### ISSUE THREAD

**Issue by rks2000** [jmir1/tachiyomi-mi#389]
### Steps to reproduce

1. I am trying to play a movie from dopebox extension
2. It is showing me error "never give up and try again later "
3. But in webview it is working fine

### Expected behavior

The movie should start playing.

### Actual behavior

But it shows me this
![IMG_20220209_195238](https://user-images.githubusercontent.com/62375786/153220386-32718d02-1024-4d01-89fe-547186f750e4.jpg)

### Crash logs

--------- beginning of system
--------- beginning of main
02-09 19:54:32.671 29553 29553 E Parcel  : Reading a NULL string not supported here.
App version: 0.12.3.6 (standard, 67c506d, 72, 2022-01-06T02:47Z)
Android version: 11 (SDK 30)
Android build ID: RMX3031_11_A.14
Device brand: realme
Device manufacturer: realme
Device name: RMX3031L1
Device model: RMX3031
Device product name: RMX3031

### Aniyomi version

App version: 0.12.3.6 (standard, 67c506d, 72, 2022-01-06T02:47Z) 

### Android version

Android version: 11 (SDK 30)

### Device

Device brand: realme Device manufacturer: realme Device name: RMX3031L1 Device model: RMX3031

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ahmedgamal17** [comment]
It means to keep trying until the video works it's a bug that I couldn't fix 👍🏼

**Comment by ahmedgamal17** [comment]
And this the wrong repo to open extension issue go to aniyomi-extensions repo
