### ISSUE TITLE
Anime Extentions & Anime Backup

### ISSUE THREAD

**Issue by jyntvrma** [jmir1/tachiyomi-mi#49]
I created backup right before uninstalling previous update(I had to for some reason)..... then I installed the latest update, I imported the backup file.....except anime almost every thing was restored.....and then I was about to install the anime extentions...but there was nothing to install.....even refreshing did not helped.....there's just a blank page....😔

**Comment by jmir1** [comment]
this was an issue with the latest automatically generated preview build. the new update will use an updated extensions library, but the update was accidentally released before it was ready.
