### ISSUE TITLE
[Bug] downloading error. 

### ISSUE THREAD

**Issue by ty-coon** [jmir1/tachiyomi-mi#62]
Anime: ancient magus bride, Mahoutsukai no Yome: Hoshi Matsu Hito
App latest version.
Anime source: 2dgirls.tech

**Comment by ty-coon** [comment]
![Screenshot_20210609_141412](https://user-images.githubusercontent.com/83224209/121324039-f8cfa080-c92d-11eb-80cb-e78bdc6518f0.jpg)

**Comment by S0T0N0** [comment]
You shit go on the lower right there it says captcha when you solved it and it says redirecting close the in app browser.

**Comment by S0T0N0** [comment]
[]()https://user-images.githubusercontent.com/72794819/121333965-8ead0080-c919-11eb-9164-a999770498e6.mp4

**Comment by ty-coon** [comment]
@S0T0N0 arse what about download crash? Is it working for your mommy arse?

**Comment by S0T0N0** [comment]
Use another source you idiot.

**Comment by ty-coon** [comment]
@S0T0N0 there's no other sources for it, 4anime.to does not work in our country.

**Comment by ty-coon** [comment]
And thanks for your sweet arse time, i used vpn for it.
