### ISSUE TITLE
Downloaded video quality selection 

### ISSUE THREAD

**Issue by 3bdullah-3bdeen** [jmir1/tachiyomi-mi#908]
### Describe your suggested feature

For example when I download episodes from animepahi it doesn't ask witch quality I would like to download, so if there was an option to set preferred download quality in the settings it would be awesome

Also it might be an issue with me phone's processing power but when I watch 1080p videos with the built in video player it would lag a bit and it would show more as you progress in the video

However when I play that same downloaded episode using VLC it would be fine

I didn't encounter issues with the 720p videos so far and that's why I said it might be the processing power 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by venkat2305** [comment]
More options for downloader 🙏

**Comment by ArminArlert31** [comment]
up up up

**Comment by GamingMajd** [comment]
Up Vote

**Comment by XxJibril** [comment]
being able to select the quality to download would be a massive QoL upgrade yeah!!!

**Comment by venkat2305** [comment]
if there are multiple streams for a preferred quality, an option to select our preferred stream would be great

**Comment by lonewolf0211** [comment]
This is already an option. Go to browse > anime extensions > pick the extension you plan to use and click settings > click gear icon and change preferences.

**Comment by XxJibril** [comment]
@lonewolf0211 wow i can't believe i missed that, thank you so much !!
